### PR TITLE
Groknet

### PR DESCRIPTION
**Pull request by praeclarumjj3**

### CODE REVIEW

**Comment by dakshitagrawal97** [comment]
You too @aniket-agarwal1999. Better commit messages please, and with an emoji at the beginning. Looks like you removed unnecessary new lines, so maybe write that as the commit message.

**Comment by aniket-agarwal1999** [comment]
Actually at the end I am gonna squash and merge all these commits into one, so I will just rename that commit message @dakshitagrawal97 :sweat_smile:

**Comment by praeclarumjj3** [comment]
> Please do take care of the spacing from the next time and also review the changes I have done in these from your next PR. Mostly a bit of refactoring should work. New lines and spaces should be used a bit more efficiently, just once view the changes I have done in GrokNet.md and also the spacing changes in README.md

Yes...will take care from next time

**Comment by dakshitagrawal97** [comment]
@praeclarumjj3 use imperative language for git commit messages.

Hence, use `correct` instead of `corrected`.

**Comment by praeclarumjj3** [comment]
> @praeclarumjj3 use imperative language for git commit messages.
> 
> Hence, use `correct` instead of `corrected`.

Noted @dakshitagrawal97

**Comment by aniket-agarwal1999** [comment]
Should I merge up then, it looks fine to me now... @dakshitagrawal97 ?

**Comment by dakshitagrawal97** [comment]
Haven't had a look at the contents, up to you @aniket-agarwal1999.

Just make sure to have proper commit messages, pipelines, similar commits as one.

Also, while writing the commit message, just start adding emojis to the beginning of the commit message, and maybe even who contributed.

Something along the lines of:
:zap: Add GrokNet paper summary

Just brings so much more life while looking at the repository commit history.

**Comment by aniket-agarwal1999** [comment]
Okay will ensure this from now on :smile:

**Comment by dakshitagrawal97** [comment]
Also, make sure the formatting is good and accurate. Doesn't hurt to be mindful while writing the markdown file. Much more pleasing to the eyes.

@praeclarumjj3 @aniket-agarwal1999

**Pull request merged**
