### PR TITLE
UAT added

### PR DESCRIPTION
**Pull request by kb10241024**

### CODE REVIEW

**Comment by aniket-agarwal1999** [comment]
@kb10241024 never merge the master branch of your project, always create a new branch for a new paper. Because of this there is a merge conflict.
Also most importantly do not use so many images to describe the loss function and other things, rather describe them in your own terms, not weighing that much on the mathematical part. Try to limit the usage of images to 1-2.
Also when done, squash the commit history to become 1 commit, rather than 15.

**Comment by aniket-agarwal1999** [comment]
@kb10241024 Any updates on this?

**Comment by kb10241024** [comment]
Sorry , it slipped from my mind 😅

**Comment by kb10241024** [comment]
Will create different PR now.

**Pull request closed without merging**
