### PR TITLE
Add Summary for MI attacks defense

### PR DESCRIPTION
**Pull request by NikharW**

### CODE REVIEW

**Comment by mr-sarthakgupta** [comment]
@NikharW please squash all commits into a single one and in the 'method' section, please include text in markdown instead of the image.

**Comment by mr-sarthakgupta** [comment]
Please include the name of the conference/journal it was published in the readme

**Comment by praeclarumjj3** [comment]
Why is this still open?

**Review by mr-sarthakgupta — APPROVED** [review]

**Comment by mr-sarthakgupta** [comment]
@NikharW please name the summary file with underscores instead of spaces

**Comment by praeclarumjj3** [comment]
It's been over a month. Is this still in progress?

**Review by mr-sarthakgupta — COMMENTED** [review]
good to go

**Comment by praeclarumjj3** [comment]
> good to go

how? there are still conflicts.

**Pull request closed without merging**
