### PR TITLE
Add summary for Unsupervised Learning of Probably Symmetric Deformable 3D Objects from Images in the Wild

### PR DESCRIPTION
**Pull request by praeclarumjj3**
…ormable 3D Objects from Images in the Wild

### CODE REVIEW

**Comment by aniket-agarwal1999** [comment]
Please improve the summary altogether, since right now the summary language in every section is pretty much a direct recreation of what is written in the original paper. The aim should be to explain the things in your own language.

**Comment by praeclarumjj3** [comment]
> Please improve the summary altogether, since right now the summary language in every section is pretty much a direct recreation of what is written in the original paper. The aim should be to explain the things in your own language.

Should I reduce the maths in the summary, because the paper mostly revolves around the mathematics?

**Comment by aniket-agarwal1999** [comment]
Umm, not necessarily. The problem right now is that most of the language you have written is rather directlt taken from paper Rather just give the paper a read and then try framing up the summary in your own language. The content that is covered right now is pretty enough, what you need to do is simplify the whole summary further in your own language.

**Comment by praeclarumjj3** [comment]
> Umm, not necessarily. The problem right now is that most of the language you have written is rather directly taken from paper Rather just give the paper a read and then try framing up the summary in your own language. The content that is covered right now is pretty enough, what you need to do is simplify the whole summary further in your own language.

Okay, thanks for the feedback! I have tried to simplify the summary. However, in some places, I had to use the authors' language to explain in the best way possible. Please have another look :)

**Pull request merged**
